# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/metadata-syntax-for-github-actions
name: 'NPM or Yarn install with caching'
description: 'Install npm dependencies with caching'
author: 'Gleb Bahmutov'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: 'yellow'
  icon: 'command'
inputs:
  useLockFile:
    description: By default, the action will use a lock file like `package-lock.json` or `yarn.lock`. You can set this option to `false` to use just `package.json`. 
    required: false
    default: 'true'
  working-directory:
    description: One or many subfolders separated by a new line character.
    required: false
  auth-token:
    description: The npm authentication token (for private packages).
    required: false

