name: example-performance
on: [pull_request]
jobs:
  # cache using npm-install
  cache1:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      # setup Node 20
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: npm install chalk
      # look at fast this action installs a single dependency
      - uses: bahmutov/npm-install@performance
        with:
          working-directory: examples/basic
          install-command: 'npm install chalk'
          cache-key-prefix: chalk5
        env:
          ACTIONS_RUNNER_DEBUG: true
          ACTIONS_STEP_DEBUG: true

  # cache using https://github.com/actions/cache
  cache2:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Caching
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: chalk-v1
        env:
          ACTIONS_RUNNER_DEBUG: true
          ACTIONS_STEP_DEBUG: true
      - name: Install just chalk
        run: npm install chalk
