name: example-yarn
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@HEAD
        working-directory: examples/yarn
      - run: npm t
        working-directory: examples/yarn
