name: example-without-lock-file
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@HEAD
        with:
          working-directory: examples/without-lock-file
          useLockFile: false
      - run: npm t
        working-directory: examples/without-lock-file
