name: example-yarn
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@HEAD
        with:
          working-directory: examples/yarn
      - run: npm t
        working-directory: examples/yarn
